language: php

php:
  - '7.1'

jobs:
  include:
  - stage: github release
    install:
      - composer install
    env:
      - BUILD_DIR=build
      - GITHUB_RELEASE_FILENAME=sub.zip
    script:
      - find ./ -type d | xargs chmod 755
      - find ./ -name '*.php' | xargs chmod 644
      - zip -r $GITHUB_RELEASE_FILENAME ./ -x "*.git*" -x "*.travis.yml*" -x "composer.*" && mkdir $BUILD_DIR && mv $GITHUB_RELEASE_FILENAME $BUILD_DIR/
    deploy:
      - provider: releases
        api_key:
          secure: qsKv+PrjI06Sw86kVTqHQNtm2ST9ounMjnQzS6A9IaahJT2L3yk7ejd37IULrZND0qzoY+hvTtyXKEU3X0aTXlnJTo27TAfS2DEE4v0o3L35WPDvTZ6LigtoR5SF6DQi3nrVLSymoTM/eBmBq2EphDUEkRMjTTaf8ZyN4fE3iHui19whjYvL1jzDOE19Pez/UaMOBBQGDkKKVcPxg/sgp7I7PThovTngjFRxMoA/ISh2GTjYDNXlketRI077Z6+1swXK3ytrQvx6JBla3wj86c2dxx5Iffe133rxkvgTIeqnZ2roK4Pp4XimjIp0j7EzQf19H3WPtSWOYeLi+lLUexLFsc2eejmR3sGmeXDasifMWqDC9XqBWMP/5LqkjYCK2qBiSTbaQArT5l5wOy7tg6LG/gXLtwXxVN8T4Z+ytW6fttQZdFRLobIAkX+cJ7xU6WYYFY+T/vngmlIes796VTnq5WBS7bibcDA9qFSkjZaIFqD5u3LGruYZ1WXczv6D7gH1MZYTH/Avb55rAbatEJV+ySpjqUaZNcDLJzMlGeq7PEyadvSNCuXjp4vWPKY02aBxLjSXAt/Us9p4G/9cPCkDK5HhwaE6WOZgKG/Q9seFqpnaZnTFbd938xX+667ZY+qmkBMK4vLqgd5cCzmv7V2LjpJJf1N+//aDEIDwqro=
        file: "$BUILD_DIR/$GITHUB_RELEASE_FILENAME"
        skip_cleanup: true
        name: "$TRAVIS_TAG"
        on:
          tags: true
          condition: $TRAVIS_TAG != *beta*
      - provider: releases
        api_key:
          secure: qsKv+PrjI06Sw86kVTqHQNtm2ST9ounMjnQzS6A9IaahJT2L3yk7ejd37IULrZND0qzoY+hvTtyXKEU3X0aTXlnJTo27TAfS2DEE4v0o3L35WPDvTZ6LigtoR5SF6DQi3nrVLSymoTM/eBmBq2EphDUEkRMjTTaf8ZyN4fE3iHui19whjYvL1jzDOE19Pez/UaMOBBQGDkKKVcPxg/sgp7I7PThovTngjFRxMoA/ISh2GTjYDNXlketRI077Z6+1swXK3ytrQvx6JBla3wj86c2dxx5Iffe133rxkvgTIeqnZ2roK4Pp4XimjIp0j7EzQf19H3WPtSWOYeLi+lLUexLFsc2eejmR3sGmeXDasifMWqDC9XqBWMP/5LqkjYCK2qBiSTbaQArT5l5wOy7tg6LG/gXLtwXxVN8T4Z+ytW6fttQZdFRLobIAkX+cJ7xU6WYYFY+T/vngmlIes796VTnq5WBS7bibcDA9qFSkjZaIFqD5u3LGruYZ1WXczv6D7gH1MZYTH/Avb55rAbatEJV+ySpjqUaZNcDLJzMlGeq7PEyadvSNCuXjp4vWPKY02aBxLjSXAt/Us9p4G/9cPCkDK5HhwaE6WOZgKG/Q9seFqpnaZnTFbd938xX+667ZY+qmkBMK4vLqgd5cCzmv7V2LjpJJf1N+//aDEIDwqro=
        file: "$BUILD_DIR/$GITHUB_RELEASE_FILENAME"
        skip_cleanup: true
        name: "$TRAVIS_TAG"
        prerelease: true
        on:
          tags: true
          condition: $TRAVIS_TAG =~ "beta"
